### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Trxgically** [Shelly7w7/HealthTag#1]
Can you make it so it doesn't mess with the Purechat nametags by any chance it basically just overrides them, thanks.

**Comment by Shelly7w7** [comment]
It isn't suspose to override 🤔, I tested it and it worked for me 🤔

**Comment by Shelly7w7** [comment]
Yeap, purechat uses ``$player->setNametag("") ;`` and I am using ``$player->setScoreTag("");``

**Comment by Trxgically** [comment]
Well I guess I'm lieing right ? It totally doesn't remove the tags from my players usernames and put the health.

**Comment by Shelly7w7** [comment]
@Flucid I have tested and confirmed it from some developers that ``setScoreTag`` doesn't messes up ``setNameTag``. What version of purechat are you using? Are you using purechat from poggit-orphanage?

**Comment by Trxgically** [comment]
I have a feeling it's just Purechat because for some players it shows the Rank above their name but for some it doesn't, maybe its because of how long their name is I have no idea.. sorry for the false issue.

**Comment by Trxgically** [comment]
Great plugin!

**Comment by Shelly7w7** [comment]
Ty :D
