### ISSUE TITLE
Error and server Crash, newest Poggit release File

### ISSUE THREAD

**Issue by suerion** [Shelly7w7/HealthTag#7]
Hello,

i had tested on my debug server the latest release File, but it crashed 2 times my whole server.

Could this error on your code, or on pocketmine? 

her is the Error from Console

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected '`', expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/HealthTag.phar/src/shelly7w7/HealthTag/Main" at line 14```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #0 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[24] shelly7w7\HealthTag\Main)```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #1 (): BaseClassLoader->{closure}(string[24] shelly7w7\HealthTag\Main)```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #2 (): spl_autoload_call(string[24] shelly7w7\HealthTag\Main)```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #3 src/pocketmine/plugin/PluginManager(167): class_exists(string[24] shelly7w7\HealthTag\Main, boolean 1)```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #4 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[69] /home/minecraft/multicraft/servers/PE_Creative/plugins/HealthTag.phar, array[2])```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #5 src/pocketmine/Server(1531): pocketmine\plugin\PluginManager->loadPlugins(string[55] /home/minecraft/multicraft/servers/PE_Creative/plugins/)```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /home/minecraft/multicraft/servers/PE_Creative/, string[55] /home/minecraft/multicraft/servers/PE_Creative/plugins/)```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #7 src/pocketmine/PocketMine(304): pocketmine\server()```

```2020-08-23 [18:11:36] [Server thread/CRITICAL]: #8 (11): require(string[93] phar:///home/minecraft/multicraft/pocketmine/PocketMine-MP.phar/src/pocketmine/P)```

**Comment by Shelly7w7** [comment]
Fixed

**Comment by suerion** [comment]
Thanks :)
